const GAME = [
  {
    img: "img/os-pacemaker.png",
    title: "جهاز تنظيم ضربات القلب",
    a: "Embedded OS",
    b: "Multi-user OS",
    answer: "a",
    why: "البرنامج مدمج في العتاد ويعمل في الخلفية — هذا Embedded operating system.",
  },
  {
    img: "img/os-single-task.png",
    title: "هاتف أساسي بسيط",
    a: "Single-task · single-user",
    b: "Multitasking · single-user",
    answer: "a",
    why: "يشغّل تطبيقًا واحدًا فقط. الهاتف الذكي مثال Multitasking · single-user.",
  },
  {
    img: "img/os-multitask.png",
    title: "هاتف ذكي بعدة تطبيقات معًا",
    a: "Single-task · single-user",
    b: "Multitasking · single-user",
    answer: "b",
    why: "مستخدم واحد + تطبيقات متعددة في الوقت نفسه = Multitasking · single-user.",
  },
  {
    img: "img/game-cloud-collab.png",
    title: "عدة أشخاص يعدّلون جدولًا على السحابة",
    a: "Multitasking · single-user",
    b: "Multi-user",
    answer: "b",
    why: "عدة مستخدمين على نفس المورد عبر server/cloud = Multi-user OS.",
  },
  {
    img: "img/os-rtos.png",
    title: "لوحة سيارة رقمية تستجيب فورًا",
    a: "Real time (RTOS)",
    b: "Entertainment software",
    answer: "a",
    why: "معالجة في الزمن الحقيقي = Real time operating system.",
  },
  {
    img: "img/game-smart-mirror.png",
    title: "مرآة حمّام تمنع التغشية",
    a: "Embedded OS",
    b: "Command line UI",
    answer: "a",
    why: "حساسات وبرنامج مدمج في العتاد = Embedded.",
  },
  {
    img: "img/ui-wimp-easy.png",
    title: "طفل يستخدم جهازًا بأيقونات كبيرة",
    a: "Graphical UI (GUI)",
    b: "Command line",
    answer: "a",
    why: "Graphical interface / WIMP — سهلة بلا برمجة؛ Adapted إن كُيّف الحجم واللون.",
  },
  {
    img: "img/game-router-cli.png",
    title: "فني يضبط موجّه شبكة بأوامر نصية",
    a: "Graphical UI",
    b: "Command line",
    answer: "b",
    why: "أوامر نصية عبر terminal = Command line interface.",
  },
  {
    img: "img/ui-menu.png",
    title: "شاشة خيارات بزر كبير في كشك",
    a: "Menu-based UI",
    b: "Real time OS",
    answer: "a",
    why: "الوظائف عبر قائمة جاهزة = Menu-based user interface.",
  },
  {
    img: "img/util-antivirus.png",
    title: "فحص أمني وحماية من الفيروسات",
    a: "Utility software",
    b: "Application software",
    answer: "a",
    why: "Antivirus / anti-malware من Utility software — يصون النظام.",
  },
  {
    img: "img/util-backup.png",
    title: "نسخ احتياطي للبيانات",
    a: "Backup software (Utility)",
    b: "Office software (Application)",
    answer: "a",
    why: "Backup software أداة مساعدة روتينية حسب مواصفات A4.",
  },
  {
    img: "img/util-driver.png",
    title: "ربط الطابعة بالحاسوب",
    a: "Device driver",
    b: "Entertainment software",
    answer: "a",
    why: "Device drivers تربط الجهاز الرقمي بالطرفيات — دور من أدوار OS.",
  },
  {
    img: "img/util-cleanup.png",
    title: "ضغط ملفات وتحليل قرص",
    a: "Compression / Disk analyser",
    b: "CAD",
    answer: "a",
    why: "Compression tools و Disk analysers من قائمة Utility software.",
  },
  {
    img: "img/app-office.png",
    title: "جداول ومستندات في المكتب",
    a: "Utility software",
    b: "Office software / Application",
    answer: "b",
    why: "Office software من Application software — ينجز عمل المستخدم.",
  },
  {
    img: "img/app-cad.png",
    title: "تصميم معماري على الشاشة",
    a: "CAD",
    b: "Firewall",
    answer: "a",
    why: "Computer-aided design (CAD) تطبيق متخصص حسب A4.",
  },
  {
    img: "img/app-comms.png",
    title: "مكالمة فيديو بين جهازين",
    a: "Communications software",
    b: "Disk partitioner",
    answer: "a",
    why: "Communications software من Application software.",
  },
  {
    img: "img/open-vs-prop.png",
    title: "كود يمكن نسخه وتعديله مجانًا",
    a: "Open source",
    b: "Proprietary",
    answer: "a",
    why: "Open source: تعاوني، مجاني، قابل للتكييف.",
  },
  {
    img: "img/app-office.png",
    title: "برنامج تشتريه ولا تغيّر شفرته",
    a: "Open source",
    b: "Proprietary",
    answer: "b",
    why: "Proprietary: ملك الشركة؛ استخدام بلا تعديل source code.",
  },
  {
    img: "img/file-jpeg.png",
    title: "صورة صغيرة لإرفاقها بالبريد",
    a: "JPEG",
    b: "RAW",
    answer: "a",
    why: "JPEG مضغوط بحجم أصغر — مناسب للمشاركة؛ مع فقدان بعض الجودة.",
  },
  {
    img: "img/file-raw.png",
    title: "صورة كاميرا تحتاج تعديلًا احترافيًا",
    a: "JPEG",
    b: "RAW",
    answer: "b",
    why: "RAW غير مضغوط وغني بالتفاصيل للتعديل — من أنواع Images في A4.",
  },
];
